# Generated by Django 2.0.5 on 2018-06-07 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('DOB', models.DateTimeField(blank=True, null=True)),
                ('DOD', models.DateTimeField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['first_name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='enter a brief summary of the book', max_length=500)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=14)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('status', models.CharField(choices=[('o', 'loan'), ('A', 'available'), ('M', 'Maintianance'), ('r', 'reversed')], default='m', help_text='displays the availabilty of a book', max_length=2)),
                ('imprint', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='enter  the unique Id for the book', primary_key=True, serialize=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='kindly enter the genre the book belongs to e.g(scientific, Fiction or Drama) ', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='enter the book genre here ', to='catalog.Genre'),
        ),
    ]
