# Generated by Django 2.0.5 on 2018-06-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180607_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_dialect', models.CharField(choices=[('E', 'English'), ('F', 'French'), ('C', 'Chinese'), ('F2', 'Farsi')], default='E', max_length=2)),
                ('book_dialect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
            ],
        ),
    ]
