# Generated by Django 2.0.5 on 2018-06-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180607_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='book_dialect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book'),
        ),
    ]
